### ISSUE TITLE
[🐛 BUG]: Remove github dependancy

### ISSUE THREAD

**Issue by BarnabyDT** [roadrunner-server/velox#28]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Currently velox always expects at least one github repository to exist in the config, this may not always be the case with peoples custom builds.

### Version

Master

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13280a6]

goroutine 1 [running]:
github.com/roadrunner-server/velox/github.NewGHRepoInfo(0xc0000a5bc0, 0xc0000ac3c0)
        ~/src/github.com/roadrunner-server/velox/github/repo.go:43 +0x26
github.com/roadrunner-server/velox/internal/commands/build.BindCommand.func1(0xc000134780?, {0x15128fb?, 0x2?, 0x2?})
        ~/src/github.com/roadrunner-server/velox/internal/commands/build/build.go:47 +0xfc
github.com/spf13/cobra.(*Command).execute(0xc000134780, {0xc0000e0660, 0x2, 0x2})
        ~/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000134500)
        ~/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        ~/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
        ~/src/github.com/roadrunner-server/velox/vx/main.go:14 +0x4b
exit status 2
```

**Comment by rustatian** [comment]
Hey 👋🏻 
Hm, never think this way. I guessed that at least logger or RPC should be in the config. But yeah, your scenario is possible for sure.

**Comment by rustatian** [comment]
Hey @BarnabyDT  👋🏻 
I tried to verify your issue, but you don't need to have any GitHub repositories (except RR itself). If you don't specify any plugin - `velox` should return an error: `return errors.New("no plugins specified in the configuration")`. RR build with no plugin has no sense (but doesn't lead to panic) 😃 thus, having at least one is mandatory.

I also turned off the `[github.plugins]` section at all (leave only token to download the RR) and used GitLab plugins, and everything seems to work fine.

![image](https://user-images.githubusercontent.com/8040338/176996005-8370e70d-c3e3-40d4-8ae9-15940a852da9.png)

---

To verify your issue, could you please send here your `velox.toml` file? Or steps to reproduce an error.
